version: '3'
services:
    forward-proxy:
        build: .
        image: http-proxy
        ports:
            - 8000:80
        environment:
            - TARGET_HOST=""
            - TARGET_PORT=""
